// Package assets is the Assets/EAM module (reference-data-model.md §9,
// BACKLOG.md R8) — FixedAsset and its DepreciationSchedule. A licensed
// module like purchasing/sales/finance, not part of every tenant's
// baseline: published by cmd/provision-tenant only when a tenant has
// actually licensed it.
//
// The depreciation arithmetic lives in this package's depreciation.go
// and is held to the deterministic-core standard (see its own file
// comment) rather than the looser one a CRUD module gets — a schedule
// that drifts by a minor unit per period is a balance-sheet error, not
// a display bug.
//
// Deliberately NOT in this slice, each for its own reason:
//   - **MaintenanceOrder** (board #20): a real entity in §9, but it
//     references FixedAsset and this card is that reference's target.
//     Filed separately and reordered behind this one.
//   - **Posting depreciation to the ledger**: the schedule this module
//     generates is the input a periodic posting run would consume
//     (debit depreciation expense, credit accumulated depreciation),
//     and the account references below exist precisely so that run has
//     somewhere to post. But the run itself is a scheduled job writing
//     journal entries — internal/kernel/ledger's hand-written,
//     human-reviewed territory plus workflow's cron trigger — and
//     bolting it onto a first CRUD slice is exactly what
//     sales.CustomerInvoice's own doc comment warned against. Filed as
//     follow-up work.
//   - **Revaluation, impairment, disposal accounting**: each is its own
//     accounting event with its own postings, not a field on this
//     entity.
package assets

import "github.com/universaltill/universal-core/internal/kernel/entity"

// FixedAsset is an owned asset being depreciated
// (reference-data-model.md §9). The three account references are what
// tie it to Finance: an asset's cost sits in one account, its
// accumulated depreciation contra-account offsets it, and each period's
// charge hits an expense account. They are optional at the Definition
// level because an asset can legitimately be registered before its
// posting accounts are decided — the posting run (follow-up work) is
// where their absence becomes an error, not data entry.
//
// currency_id is carried explicitly rather than assumed: cost and
// salvage are money, and depreciation.MinorUnits needs the currency's
// scale to convert them without guessing that everything is 2dp.
func FixedAsset() *entity.Definition {
	return &entity.Definition{
		EntityType:     "FixedAsset",
		Version:        1,
		Module:         "assets",
		StatusTypeCode: "fixed_asset_status",
		Fields: []entity.Field{
			// asset_number is the natural key, same application-level
			// convention as po_number/so_number/Item.sku.
			{Name: "asset_number", Type: entity.FieldString, Required: true},
			{Name: "name", Type: entity.FieldI18nText, Required: true},
			{Name: "acquisition_date", Type: entity.FieldDate, Required: true},
			{Name: "cost", Type: entity.FieldNumber, Required: true},
			{Name: "salvage_value", Type: entity.FieldNumber, Default: float64(0)},
			// Useful life in MONTHS, not years: depreciation is charged
			// monthly, and storing years would force every consumer to
			// re-derive months and disagree about how to handle a
			// part-year life.
			{Name: "useful_life_months", Type: entity.FieldNumber, Required: true},
			{Name: "depreciation_method", Type: entity.FieldEnum, Required: true,
				// Only the method depreciation.Build actually implements
				// is offered — an enum value with no implementation
				// behind it is a promise the schedule generator breaks.
				EnumValues: []string{"straight_line"},
				Default:    "straight_line"},
			{Name: "location", Type: entity.FieldString},
			{Name: "currency_id", Type: entity.FieldReference, Target: "Currency"},
			{Name: "asset_account_id", Type: entity.FieldReference, Target: "Account"},
			{Name: "depreciation_expense_account_id", Type: entity.FieldReference, Target: "Account"},
			{Name: "accumulated_depreciation_account_id", Type: entity.FieldReference, Target: "Account"},
			{Name: "status_id", Type: entity.FieldReference, Required: true, Target: "Status"},
		},
		Relationships: []entity.Relationship{
			// Composition, not a related list: a schedule row has no
			// meaning without its asset, and regenerating a schedule
			// replaces the set wholesale. ParentField is what
			// loadMasterDetailChildren looks up for the form's
			// master-detail section.
			{Name: "schedule", Kind: entity.RelationComposition, Target: "DepreciationSchedule", ParentField: "fixed_asset_id"},
		},
	}
}

// DepreciationSchedule is one period's charge and the resulting book
// value (reference-data-model.md §9) — generated by depreciation.Build,
// not hand-entered, though nothing structurally prevents a correction:
// these are ordinary records through the same guarded engine, so an
// adjustment is auditable like any other change rather than a silent
// recomputation.
//
// Amounts are stored as ordinary FieldNumber values (the engine's
// float64) because that is what every other money field in this kernel
// stores today; the exact arithmetic happens in integer minor units and
// is converted once at the boundary. When the kernel grows a real money
// type, this entity converts with the rest of them.
func DepreciationSchedule() *entity.Definition {
	return &entity.Definition{
		EntityType: "DepreciationSchedule",
		Version:    1,
		Module:     "assets",
		Fields: []entity.Field{
			{Name: "fixed_asset_id", Type: entity.FieldReference, Required: true, Target: "FixedAsset"},
			{Name: "sequence", Type: entity.FieldNumber, Required: true},
			// period_end is the last day of the month this row covers —
			// the date a posting for it carries.
			{Name: "period_end", Type: entity.FieldDate, Required: true},
			{Name: "depreciation_amount", Type: entity.FieldNumber, Required: true},
			{Name: "book_value", Type: entity.FieldNumber, Required: true},
			// posted_at stays empty until a ledger posting run (follow-up
			// work) claims the row. Present from the start so that run
			// doesn't need a version-bump migration to become
			// idempotent — the same foresight PurchaseOrder's own
			// status_id doc comment says was missing there.
			{Name: "posted_at", Type: entity.FieldDate},
		},
	}
}

// All returns every Definition this module adds — the set a tenant gets
// once Assets is one of their licensed modules (seed.go's Publish).
func All() []*entity.Definition {
	return []*entity.Definition{
		FixedAsset(),
		DepreciationSchedule(),
	}
}
